#!/usr/bin/env python3
"""
One-shot translator for the `airdrop.*` namespace and `tools.items.airdrop`
strings across all non-EN locales.

Hand-translated rather than machine-translated because the tone matters
(crypto-native, terse, technical) and ICU MessageFormat plurals must be
correct per CLDR rules for each language.

Run from the pandabox-v2/ root:
    python3 scripts/translate-airdrop.py
"""

import json
import pathlib

# Per-locale translations. Technical terms (Sui, SUI, PTB, CSV, JSON,
# Pandabox) deliberately untranslated.

TRANSLATIONS = {
    "de": {
        "items_airdrop": {
            "name": "Airdrop · Massenversand",
            "tagline": "Verteile einen Sui-Token in einer einzigen signierten Transaktion an bis zu 300 Wallets.",
            "description": "CSV einfügen, einmal signieren, Empfänger erhalten alles. Gebaut für Token-Launches, Beitragender-Belohnungen und Community-Drops, bei denen einzelne Zahlungen keine Option sind.",
            "cap1": "Massenversand · bis zu 300 Empfänger pro signierter PTB",
            "cap2": "Jede Adresse wird vor dem Signieren lokal validiert",
            "cap3": "Pauschale SUI-Gebühr pro Empfänger · keine Admin-Override, keine Sperren",
        },
        "airdrop": {
            "metaTitle": "Airdrop · Pandabox",
            "eyebrow": "Onchain · Airdrop",
            "headline": "Eine Signatur. Viele Wallets.",
            "subtitle": "Verteile einen Sui-Token in einer einzigen signierten PTB an eine Empfängerliste. Der Vertrag setzt das Limit, die Gebühr und die Summen durch — kein Off-Chain-Vertrauen erforderlich.",
            "ctaCompose": "Airdrop erstellen",
            "ctaActivity": "Aktuelle Airdrops",
            "statFee": "Gebühr / Empfänger",
            "statMax": "Max / Batch",
            "statLifetime": "Gesamt versendet",
            "statStatus": "Status",
            "statStatusLive": "Live",
            "statStatusPaused": "Pausiert",
            "statSource": "Live vom Sui Mainnet",
            "statRevalidate": "Aktualisiert alle 60 s",
            "traitOneSig": "Eine Signatur",
            "traitAtomic": "Atomar — alles oder nichts",
            "traitAnyCoin": "Jeder Sui-Token-Typ",
            "traitFee": "{fee} SUI pro Empfänger",
            "traitLearn": "So funktionieren Airdrops",
            "panelEyebrow": "Erstellen",
            "panelTitle": "Empfängerliste",
            "panelEmpty": "CSV einfügen, Datei ablegen oder JSON importieren, um zu starten.",
            "panelPlaceholder": "Liste hier ablegen — eine Adresse und Menge pro Zeile, oder JSON einfügen.",
            "howEyebrow": "So funktioniert es",
            "howTitle": "Drei Schritte von der Liste zur Ausführung.",
            "howStep1Title": "Token auswählen",
            "howStep1Body": "Wähle einen beliebigen Sui-Token aus deinem Bestand. Der Picker zeigt dein verfügbares Guthaben pro Asset, sortiert nach Bestandsgröße.",
            "howStep2Title": "Empfängerliste einfügen",
            "howStep2Body": "CSV einfügen oder Datei ablegen. Jede Adresse wird vor dem Signieren lokal geprüft — ungültige Zeilen werden direkt angezeigt, nicht erst hinterher.",
            "howStep3Title": "Einmal signieren, in einer PTB ausführen",
            "howStep3Body": "Der Vertrag verteilt den Token atomar an alle Empfänger. Schlägt eine einzige Übertragung fehl, wird der gesamte Batch zurückgesetzt — keine Teil-Drops, keine hängenden Transaktionen.",
            "activityEyebrow": "Über Pandabox",
            "activityTitle": "Aktuelle Airdrops",
            "activityEmpty": "Noch keine Airdrops in diesem Paket — deiner könnte der erste sein.",
            "activityCount": "{count, plural, one {# Airdrop} other {# Airdrops}}",
        },
    },
    "es": {
        "items_airdrop": {
            "name": "Airdrop · Envío masivo",
            "tagline": "Distribuye un token Sui a hasta 300 wallets en una sola transacción firmada.",
            "description": "Pega un CSV, firma una vez, observa cómo los destinatarios reciben. Diseñado para lanzamientos de tokens, recompensas para colaboradores y drops comunitarios donde firmar pago por pago no es opción.",
            "cap1": "Envío masivo · hasta 300 destinatarios por PTB firmada",
            "cap2": "Cada dirección validada localmente antes de firmar",
            "cap3": "Tarifa fija en SUI por destinatario · sin anulación de admin, sin retenciones",
        },
        "airdrop": {
            "metaTitle": "Airdrop · Pandabox",
            "eyebrow": "Onchain · Airdrop",
            "headline": "Una firma. Muchas wallets.",
            "subtitle": "Distribuye un token Sui a una lista de destinatarios en una sola PTB firmada. El contrato impone el límite, la tarifa y los totales — no se requiere confianza fuera de la cadena.",
            "ctaCompose": "Crear airdrop",
            "ctaActivity": "Airdrops recientes",
            "statFee": "Tarifa / destinatario",
            "statMax": "Máx. / lote",
            "statLifetime": "Envíos totales",
            "statStatus": "Estado",
            "statStatusLive": "En vivo",
            "statStatusPaused": "Pausado",
            "statSource": "En vivo desde Sui mainnet",
            "statRevalidate": "Se actualiza cada 60 s",
            "traitOneSig": "Una firma",
            "traitAtomic": "Atómico — todo o nada",
            "traitAnyCoin": "Cualquier tipo de token Sui",
            "traitFee": "{fee} SUI por destinatario",
            "traitLearn": "Cómo funcionan los airdrops",
            "panelEyebrow": "Crear",
            "panelTitle": "Lista de destinatarios",
            "panelEmpty": "Pega un CSV, arrastra un archivo o importa JSON para empezar.",
            "panelPlaceholder": "Coloca tu lista aquí — una dirección y un monto por línea, o pega JSON.",
            "howEyebrow": "Cómo funciona",
            "howTitle": "Tres pasos de la lista a la ejecución.",
            "howStep1Title": "Elige un token",
            "howStep1Body": "Selecciona cualquier tipo de token Sui que tengas. El selector muestra tu saldo disponible por activo, ordenado por tamaño.",
            "howStep2Title": "Carga la lista de destinatarios",
            "howStep2Body": "Pega un CSV o arrastra un archivo. Cada dirección se valida localmente antes de firmar — las filas inválidas se muestran de inmediato, no después.",
            "howStep3Title": "Firma una vez, ejecuta en una PTB",
            "howStep3Body": "El contrato distribuye el token a todos los destinatarios de forma atómica. Si una sola transferencia falla, el lote completo se revierte — sin entregas parciales, sin transacciones atascadas.",
            "activityEyebrow": "En toda Pandabox",
            "activityTitle": "Airdrops recientes",
            "activityEmpty": "Aún no hay airdrops en este paquete — el tuyo podría ser el primero.",
            "activityCount": "{count, plural, one {# airdrop} other {# airdrops}}",
        },
    },
    "id": {
        "items_airdrop": {
            "name": "Airdrop · Kirim massal",
            "tagline": "Kirim koin Sui ke hingga 300 wallet dalam satu transaksi yang ditandatangani.",
            "description": "Tempel CSV, tanda tangani sekali, lihat penerima terisi. Dibuat untuk peluncuran token, hadiah kontributor, dan drop komunitas di mana menandatangani pembayaran satu per satu bukanlah pilihan.",
            "cap1": "Kirim massal · hingga 300 penerima per PTB",
            "cap2": "Setiap alamat divalidasi secara lokal sebelum Anda tanda tangani",
            "cap3": "Biaya SUI tetap per penerima · tanpa override admin, tanpa penahanan",
        },
        "airdrop": {
            "metaTitle": "Airdrop · Pandabox",
            "eyebrow": "Onchain · Airdrop",
            "headline": "Satu tanda tangan. Banyak wallet.",
            "subtitle": "Kirim koin Sui ke daftar penerima dalam satu PTB yang ditandatangani. Kontrak menerapkan batas, biaya, dan total — tidak diperlukan kepercayaan di luar rantai.",
            "ctaCompose": "Susun airdrop",
            "ctaActivity": "Airdrop terbaru",
            "statFee": "Biaya / penerima",
            "statMax": "Maks / batch",
            "statLifetime": "Total dikirim",
            "statStatus": "Status",
            "statStatusLive": "Aktif",
            "statStatusPaused": "Dijeda",
            "statSource": "Langsung dari Sui mainnet",
            "statRevalidate": "Diperbarui setiap 60 detik",
            "traitOneSig": "Satu tanda tangan",
            "traitAtomic": "Atomik — semua atau tidak sama sekali",
            "traitAnyCoin": "Tipe koin Sui apa pun",
            "traitFee": "{fee} SUI per penerima",
            "traitLearn": "Cara kerja airdrop",
            "panelEyebrow": "Susun",
            "panelTitle": "Daftar penerima",
            "panelEmpty": "Tempel CSV, jatuhkan file, atau impor JSON untuk memulai.",
            "panelPlaceholder": "Jatuhkan daftar Anda di sini — satu alamat dan jumlah per baris, atau tempel JSON.",
            "howEyebrow": "Cara kerjanya",
            "howTitle": "Tiga langkah dari daftar ke selesai.",
            "howStep1Title": "Pilih koin",
            "howStep1Body": "Pilih tipe koin Sui apa pun yang Anda miliki. Pemilih menampilkan saldo yang dapat digunakan per aset, diurutkan berdasarkan ukuran kepemilikan.",
            "howStep2Title": "Jatuhkan daftar penerima",
            "howStep2Body": "Tempel CSV atau jatuhkan file. Setiap alamat divalidasi secara lokal sebelum Anda tanda tangani — baris yang tidak valid ditampilkan langsung, bukan setelah fakta.",
            "howStep3Title": "Tanda tangani sekali, selesaikan dalam satu PTB",
            "howStep3Body": "Kontrak mendistribusikan koin ke setiap penerima secara atomik. Jika satu transfer gagal, seluruh batch dibatalkan — tidak ada drop parsial, tidak ada transaksi yang macet.",
            "activityEyebrow": "Di seluruh Pandabox",
            "activityTitle": "Airdrop terbaru",
            "activityEmpty": "Belum ada airdrop di paket ini — milik Anda bisa jadi yang pertama.",
            "activityCount": "{count, plural, other {# airdrop}}",
        },
    },
    "it": {
        "items_airdrop": {
            "name": "Airdrop · Invio massivo",
            "tagline": "Distribuisci un token Sui a un massimo di 300 wallet in una singola transazione firmata.",
            "description": "Incolla un CSV, firma una volta, guarda i destinatari riempirsi. Pensato per lanci di token, ricompense per contributori e drop di comunità in cui firmare un pagamento alla volta non è un'opzione.",
            "cap1": "Invio massivo · fino a 300 destinatari per PTB firmata",
            "cap2": "Ogni indirizzo è validato localmente prima della firma",
            "cap3": "Commissione SUI fissa per destinatario · nessun override admin, nessuna trattenuta",
        },
        "airdrop": {
            "metaTitle": "Airdrop · Pandabox",
            "eyebrow": "Onchain · Airdrop",
            "headline": "Una firma. Molti wallet.",
            "subtitle": "Distribuisci un token Sui a una lista di destinatari in una singola PTB firmata. Il contratto impone il limite, la commissione e i totali — nessuna fiducia off-chain richiesta.",
            "ctaCompose": "Crea airdrop",
            "ctaActivity": "Airdrop recenti",
            "statFee": "Commissione / destinatario",
            "statMax": "Max / batch",
            "statLifetime": "Invii totali",
            "statStatus": "Stato",
            "statStatusLive": "Attivo",
            "statStatusPaused": "In pausa",
            "statSource": "In diretta da Sui mainnet",
            "statRevalidate": "Aggiornato ogni 60 s",
            "traitOneSig": "Una firma",
            "traitAtomic": "Atomico — tutto o niente",
            "traitAnyCoin": "Qualsiasi tipo di token Sui",
            "traitFee": "{fee} SUI per destinatario",
            "traitLearn": "Come funzionano gli airdrop",
            "panelEyebrow": "Crea",
            "panelTitle": "Lista destinatari",
            "panelEmpty": "Incolla un CSV, trascina un file o importa JSON per iniziare.",
            "panelPlaceholder": "Trascina la tua lista qui — un indirizzo e un importo per riga, o incolla JSON.",
            "howEyebrow": "Come funziona",
            "howTitle": "Tre passi dalla lista all'esecuzione.",
            "howStep1Title": "Scegli un token",
            "howStep1Body": "Seleziona qualsiasi tipo di token Sui che possiedi. Il selettore mostra il saldo disponibile per asset, ordinato per dimensione.",
            "howStep2Title": "Carica la lista destinatari",
            "howStep2Body": "Incolla un CSV o trascina un file. Ogni indirizzo è validato localmente prima della firma — le righe non valide sono mostrate subito, non dopo.",
            "howStep3Title": "Firma una volta, esegui in una PTB",
            "howStep3Body": "Il contratto distribuisce il token a ogni destinatario in modo atomico. Se un singolo trasferimento fallisce, l'intero batch viene annullato — nessun drop parziale, nessuna transazione bloccata.",
            "activityEyebrow": "Su tutta Pandabox",
            "activityTitle": "Airdrop recenti",
            "activityEmpty": "Ancora nessun airdrop in questo pacchetto — il tuo potrebbe essere il primo.",
            "activityCount": "{count, plural, one {# airdrop} other {# airdrop}}",
        },
    },
    "ja": {
        "items_airdrop": {
            "name": "エアドロップ · 一括送信",
            "tagline": "1回の署名済みトランザクションで最大300ウォレットにSuiコインを配布。",
            "description": "CSVを貼り付けて1回署名するだけで、受取人が順次受け取ります。トークンローンチ、貢献者報酬、コミュニティドロップなど、個別に署名する選択肢がない場合に最適です。",
            "cap1": "一括送信 · 署名済みPTBごとに最大300受取人",
            "cap2": "署名前にすべてのアドレスをローカルで検証",
            "cap3": "受取人ごとの固定SUI手数料 · 管理者によるオーバーライドや保留なし",
        },
        "airdrop": {
            "metaTitle": "エアドロップ · Pandabox",
            "eyebrow": "オンチェーン · エアドロップ",
            "headline": "1回の署名。多数のウォレット。",
            "subtitle": "1回の署名済みPTBで、受取人リストにSuiコインを配布。コントラクトが上限、手数料、合計を強制し、オフチェーンの信頼は不要です。",
            "ctaCompose": "エアドロップを作成",
            "ctaActivity": "最近のエアドロップ",
            "statFee": "手数料 / 受取人",
            "statMax": "最大 / バッチ",
            "statLifetime": "累計送信数",
            "statStatus": "状態",
            "statStatusLive": "稼働中",
            "statStatusPaused": "一時停止中",
            "statSource": "Suiメインネットからライブ",
            "statRevalidate": "60秒ごとに更新",
            "traitOneSig": "1回の署名",
            "traitAtomic": "アトミック — オール・オア・ナッシング",
            "traitAnyCoin": "あらゆるSuiコインタイプ",
            "traitFee": "受取人あたり{fee} SUI",
            "traitLearn": "エアドロップの仕組み",
            "panelEyebrow": "作成",
            "panelTitle": "受取人リスト",
            "panelEmpty": "CSVを貼り付け、ファイルをドロップ、またはJSONをインポートして開始してください。",
            "panelPlaceholder": "ここにリストをドロップしてください — 1行に1つのアドレスと金額、またはJSONを貼り付け。",
            "howEyebrow": "仕組み",
            "howTitle": "リストから完了まで3ステップ。",
            "howStep1Title": "コインを選択",
            "howStep1Body": "保有しているSuiコインタイプを選択。ピッカーは保有額順に使用可能残高を表示します。",
            "howStep2Title": "受取人リストをドロップ",
            "howStep2Body": "CSVを貼り付けるかファイルをドロップ。署名前にすべてのアドレスがローカルで検証され、無効な行は即座に表示されます。",
            "howStep3Title": "1回署名して、1つのPTBで完了",
            "howStep3Body": "コントラクトはすべての受取人にコインをアトミックに配布します。1つでも転送が失敗すると、バッチ全体がロールバックされます — 部分配布も詰まったトランザクションもありません。",
            "activityEyebrow": "Pandabox全体",
            "activityTitle": "最近のエアドロップ",
            "activityEmpty": "このパッケージにはまだエアドロップがありません — あなたが最初になれるかもしれません。",
            "activityCount": "{count, plural, other {#件のエアドロップ}}",
        },
    },
    "ko": {
        "items_airdrop": {
            "name": "에어드롭 · 대량 전송",
            "tagline": "단일 서명 트랜잭션으로 최대 300개 지갑에 Sui 코인을 분배합니다.",
            "description": "CSV를 붙여넣고 한 번 서명하면 수신자에게 차례로 도착합니다. 토큰 출시, 기여자 보상, 커뮤니티 드롭처럼 개별 결제 서명이 비효율적인 상황을 위해 설계되었습니다.",
            "cap1": "대량 전송 · 서명된 PTB당 최대 300명",
            "cap2": "서명 전 모든 주소를 로컬에서 검증",
            "cap3": "수신자당 정액 SUI 수수료 · 관리자 오버라이드 없음, 보류 없음",
        },
        "airdrop": {
            "metaTitle": "에어드롭 · Pandabox",
            "eyebrow": "온체인 · 에어드롭",
            "headline": "한 번의 서명. 다수의 지갑.",
            "subtitle": "단일 서명된 PTB로 수신자 목록에 Sui 코인을 분배합니다. 컨트랙트가 한도, 수수료, 합계를 강제하므로 오프체인 신뢰가 필요 없습니다.",
            "ctaCompose": "에어드롭 작성",
            "ctaActivity": "최근 에어드롭",
            "statFee": "수수료 / 수신자",
            "statMax": "최대 / 배치",
            "statLifetime": "누적 전송",
            "statStatus": "상태",
            "statStatusLive": "활성",
            "statStatusPaused": "일시정지",
            "statSource": "Sui 메인넷에서 실시간",
            "statRevalidate": "60초마다 갱신",
            "traitOneSig": "한 번의 서명",
            "traitAtomic": "원자적 — 전부 아니면 전무",
            "traitAnyCoin": "모든 Sui 코인 타입",
            "traitFee": "수신자당 {fee} SUI",
            "traitLearn": "에어드롭 작동 방식",
            "panelEyebrow": "작성",
            "panelTitle": "수신자 목록",
            "panelEmpty": "CSV 붙여넣기, 파일 드롭, 또는 JSON 가져오기로 시작하세요.",
            "panelPlaceholder": "여기에 목록을 드롭하세요 — 한 줄에 주소와 금액 하나씩, 또는 JSON 붙여넣기.",
            "howEyebrow": "작동 방식",
            "howTitle": "목록에서 완료까지 3단계.",
            "howStep1Title": "코인 선택",
            "howStep1Body": "보유한 Sui 코인 타입을 선택하세요. 피커는 보유 규모순으로 자산별 사용 가능 잔액을 표시합니다.",
            "howStep2Title": "수신자 목록 드롭",
            "howStep2Body": "CSV 붙여넣기 또는 파일 드롭. 서명 전에 모든 주소가 로컬에서 검증되어 무효한 행은 즉시 표시됩니다.",
            "howStep3Title": "한 번 서명, 하나의 PTB로 완료",
            "howStep3Body": "컨트랙트가 모든 수신자에게 코인을 원자적으로 분배합니다. 단일 전송 하나라도 실패하면 배치 전체가 롤백됩니다 — 부분 드롭도, 멈춘 트랜잭션도 없습니다.",
            "activityEyebrow": "Pandabox 전체",
            "activityTitle": "최근 에어드롭",
            "activityEmpty": "아직 이 패키지에 에어드롭이 없습니다 — 당신이 첫 번째가 될 수 있습니다.",
            "activityCount": "{count, plural, other {에어드롭 #건}}",
        },
    },
    "pl": {
        "items_airdrop": {
            "name": "Airdrop · Wysyłka masowa",
            "tagline": "Dystrybuuj token Sui do maksymalnie 300 portfeli w jednej podpisanej transakcji.",
            "description": "Wklej CSV, podpisz raz, obserwuj jak odbiorcy otrzymują tokeny. Stworzone dla premier tokenów, nagród dla współtwórców i drop'ów społecznościowych, gdzie podpisywanie pojedynczych płatności nie wchodzi w grę.",
            "cap1": "Wysyłka masowa · do 300 odbiorców na podpisaną PTB",
            "cap2": "Każdy adres walidowany lokalnie przed podpisem",
            "cap3": "Stała opłata SUI za odbiorcę · brak nadpisania administracyjnego, brak blokad",
        },
        "airdrop": {
            "metaTitle": "Airdrop · Pandabox",
            "eyebrow": "Onchain · Airdrop",
            "headline": "Jeden podpis. Wiele portfeli.",
            "subtitle": "Dystrybuuj token Sui do listy odbiorców w jednej podpisanej PTB. Kontrakt wymusza limit, opłatę i sumy — bez konieczności zaufania poza łańcuchem.",
            "ctaCompose": "Utwórz airdrop",
            "ctaActivity": "Ostatnie airdropy",
            "statFee": "Opłata / odbiorca",
            "statMax": "Maks / partia",
            "statLifetime": "Wysłane łącznie",
            "statStatus": "Status",
            "statStatusLive": "Aktywny",
            "statStatusPaused": "Wstrzymany",
            "statSource": "Na żywo z Sui mainnet",
            "statRevalidate": "Odświeża się co 60 s",
            "traitOneSig": "Jeden podpis",
            "traitAtomic": "Atomowy — wszystko albo nic",
            "traitAnyCoin": "Dowolny typ tokenu Sui",
            "traitFee": "{fee} SUI na odbiorcę",
            "traitLearn": "Jak działają airdropy",
            "panelEyebrow": "Utwórz",
            "panelTitle": "Lista odbiorców",
            "panelEmpty": "Wklej CSV, upuść plik lub zaimportuj JSON, aby rozpocząć.",
            "panelPlaceholder": "Upuść swoją listę tutaj — jeden adres i kwota na linię, lub wklej JSON.",
            "howEyebrow": "Jak to działa",
            "howTitle": "Trzy kroki od listy do wykonania.",
            "howStep1Title": "Wybierz token",
            "howStep1Body": "Wybierz dowolny typ tokenu Sui, który posiadasz. Selektor pokazuje dostępne saldo na aktywo, posortowane według wielkości posiadanych środków.",
            "howStep2Title": "Wstaw listę odbiorców",
            "howStep2Body": "Wklej CSV lub upuść plik. Każdy adres jest walidowany lokalnie przed podpisem — nieprawidłowe wiersze są pokazywane od razu, a nie po fakcie.",
            "howStep3Title": "Podpisz raz, wykonaj w jednej PTB",
            "howStep3Body": "Kontrakt dystrybuuje token do każdego odbiorcy atomowo. Jeśli pojedynczy transfer się nie powiedzie, cała partia jest cofana — brak częściowych dropów, brak utkniętych transakcji.",
            "activityEyebrow": "W całej Pandabox",
            "activityTitle": "Ostatnie airdropy",
            "activityEmpty": "Brak airdropów w tym pakiecie — Twój może być pierwszy.",
            "activityCount": "{count, plural, one {# airdrop} few {# airdropy} many {# airdropów} other {# airdropu}}",
        },
    },
    "ru": {
        "items_airdrop": {
            "name": "Аирдроп · Массовая рассылка",
            "tagline": "Распределите токен Sui до 300 кошельков в одной подписанной транзакции.",
            "description": "Вставьте CSV, подпишите один раз, наблюдайте за получателями. Создан для запусков токенов, наград контрибьюторам и комьюнити-дропов, где подписывать каждый платёж отдельно — не вариант.",
            "cap1": "Массовая рассылка · до 300 получателей за подписанную PTB",
            "cap2": "Каждый адрес валидируется локально перед подписью",
            "cap3": "Фиксированная комиссия SUI с получателя · без админ-оверрайда, без блокировок",
        },
        "airdrop": {
            "metaTitle": "Аирдроп · Pandabox",
            "eyebrow": "Onchain · Аирдроп",
            "headline": "Одна подпись. Множество кошельков.",
            "subtitle": "Распределите токен Sui по списку получателей в одной подписанной PTB. Контракт обеспечивает лимит, комиссию и итоги — без офчейн-доверия.",
            "ctaCompose": "Создать аирдроп",
            "ctaActivity": "Последние аирдропы",
            "statFee": "Комиссия / получатель",
            "statMax": "Макс / партия",
            "statLifetime": "Всего отправлено",
            "statStatus": "Статус",
            "statStatusLive": "Активен",
            "statStatusPaused": "На паузе",
            "statSource": "В реальном времени из Sui mainnet",
            "statRevalidate": "Обновляется каждые 60 с",
            "traitOneSig": "Одна подпись",
            "traitAtomic": "Атомарно — всё или ничего",
            "traitAnyCoin": "Любой тип токена Sui",
            "traitFee": "{fee} SUI на получателя",
            "traitLearn": "Как работают аирдропы",
            "panelEyebrow": "Создать",
            "panelTitle": "Список получателей",
            "panelEmpty": "Вставьте CSV, перетащите файл или импортируйте JSON, чтобы начать.",
            "panelPlaceholder": "Перетащите список сюда — один адрес и сумма на строку, или вставьте JSON.",
            "howEyebrow": "Как это работает",
            "howTitle": "Три шага от списка до выполнения.",
            "howStep1Title": "Выберите токен",
            "howStep1Body": "Выберите любой тип токена Sui, который у вас есть. Селектор показывает доступный баланс по каждому активу, отсортированный по размеру.",
            "howStep2Title": "Загрузите список получателей",
            "howStep2Body": "Вставьте CSV или перетащите файл. Каждый адрес проверяется локально перед подписью — невалидные строки показываются сразу, а не постфактум.",
            "howStep3Title": "Подпишите раз, выполните в одной PTB",
            "howStep3Body": "Контракт атомарно распределяет токен между всеми получателями. Если хоть один перевод не пройдёт, вся партия откатывается — без частичных дропов, без застрявших транзакций.",
            "activityEyebrow": "По всей Pandabox",
            "activityTitle": "Последние аирдропы",
            "activityEmpty": "На этом пакете пока нет аирдропов — ваш может стать первым.",
            "activityCount": "{count, plural, one {# аирдроп} few {# аирдропа} many {# аирдропов} other {# аирдропа}}",
        },
    },
    "vi": {
        "items_airdrop": {
            "name": "Airdrop · Gửi hàng loạt",
            "tagline": "Phân phối token Sui đến tối đa 300 ví trong một giao dịch đã ký.",
            "description": "Dán CSV, ký một lần, người nhận sẽ được phân phối lần lượt. Được thiết kế cho ra mắt token, phần thưởng cộng tác viên và drop cộng đồng nơi ký từng giao dịch một không phải là lựa chọn.",
            "cap1": "Gửi hàng loạt · tối đa 300 người nhận mỗi PTB đã ký",
            "cap2": "Mỗi địa chỉ được xác thực cục bộ trước khi bạn ký",
            "cap3": "Phí SUI cố định trên mỗi người nhận · không có override admin, không có giữ lại",
        },
        "airdrop": {
            "metaTitle": "Airdrop · Pandabox",
            "eyebrow": "Onchain · Airdrop",
            "headline": "Một chữ ký. Nhiều ví.",
            "subtitle": "Phân phối token Sui đến danh sách người nhận trong một PTB đã ký duy nhất. Hợp đồng thực thi giới hạn, phí và tổng số — không cần niềm tin ngoài chuỗi.",
            "ctaCompose": "Tạo airdrop",
            "ctaActivity": "Airdrop gần đây",
            "statFee": "Phí / người nhận",
            "statMax": "Tối đa / lô",
            "statLifetime": "Tổng đã gửi",
            "statStatus": "Trạng thái",
            "statStatusLive": "Hoạt động",
            "statStatusPaused": "Tạm dừng",
            "statSource": "Trực tiếp từ Sui mainnet",
            "statRevalidate": "Cập nhật mỗi 60 giây",
            "traitOneSig": "Một chữ ký",
            "traitAtomic": "Nguyên tử — tất cả hoặc không có gì",
            "traitAnyCoin": "Bất kỳ loại token Sui nào",
            "traitFee": "{fee} SUI mỗi người nhận",
            "traitLearn": "Cách airdrop hoạt động",
            "panelEyebrow": "Tạo",
            "panelTitle": "Danh sách người nhận",
            "panelEmpty": "Dán CSV, thả tệp hoặc nhập JSON để bắt đầu.",
            "panelPlaceholder": "Thả danh sách của bạn tại đây — một địa chỉ và số lượng mỗi dòng, hoặc dán JSON.",
            "howEyebrow": "Cách hoạt động",
            "howTitle": "Ba bước từ danh sách đến hoàn tất.",
            "howStep1Title": "Chọn token",
            "howStep1Body": "Chọn bất kỳ loại token Sui nào bạn đang giữ. Bộ chọn hiển thị số dư khả dụng theo từng tài sản, được sắp xếp theo quy mô nắm giữ.",
            "howStep2Title": "Thả danh sách người nhận",
            "howStep2Body": "Dán CSV hoặc thả tệp. Mọi địa chỉ được xác thực cục bộ trước khi bạn ký — các hàng không hợp lệ được hiển thị ngay, không phải sau khi đã thực hiện.",
            "howStep3Title": "Ký một lần, hoàn tất trong một PTB",
            "howStep3Body": "Hợp đồng phân phối token đến từng người nhận một cách nguyên tử. Nếu một chuyển khoản đơn lẻ thất bại, toàn bộ lô sẽ được hoàn nguyên — không có drop một phần, không có giao dịch bị kẹt.",
            "activityEyebrow": "Trên toàn Pandabox",
            "activityTitle": "Airdrop gần đây",
            "activityEmpty": "Chưa có airdrop nào trên gói này — của bạn có thể là đầu tiên.",
            "activityCount": "{count, plural, other {# airdrop}}",
        },
    },
    "zh-CN": {
        "items_airdrop": {
            "name": "空投 · 批量发送",
            "tagline": "在一笔签名交易中将 Sui 代币分发到最多 300 个钱包。",
            "description": "粘贴 CSV，签名一次,接收者依次到账。专为代币发行、贡献者奖励和社区空投而设计 —— 适用于无法逐笔签名的场景。",
            "cap1": "批量发送 · 每笔签名 PTB 最多 300 个接收者",
            "cap2": "签名前在本地验证每个地址",
            "cap3": "按接收者收取固定 SUI 费用 · 无管理员覆盖，无保留",
        },
        "airdrop": {
            "metaTitle": "空投 · Pandabox",
            "eyebrow": "链上 · 空投",
            "headline": "一次签名。多个钱包。",
            "subtitle": "在一笔签名 PTB 中将 Sui 代币分发到接收者列表。合约强制执行上限、费用和总额 —— 无需链下信任。",
            "ctaCompose": "创建空投",
            "ctaActivity": "最近空投",
            "statFee": "费用 / 接收者",
            "statMax": "最大 / 批次",
            "statLifetime": "累计发送",
            "statStatus": "状态",
            "statStatusLive": "运行中",
            "statStatusPaused": "已暂停",
            "statSource": "Sui 主网实时",
            "statRevalidate": "每 60 秒刷新",
            "traitOneSig": "一次签名",
            "traitAtomic": "原子化 —— 全部成功或全部回滚",
            "traitAnyCoin": "任意 Sui 代币类型",
            "traitFee": "每接收者 {fee} SUI",
            "traitLearn": "空投工作原理",
            "panelEyebrow": "创建",
            "panelTitle": "接收者列表",
            "panelEmpty": "粘贴 CSV、拖放文件或导入 JSON 开始。",
            "panelPlaceholder": "在此处拖放你的列表 —— 每行一个地址和金额，或粘贴 JSON。",
            "howEyebrow": "工作原理",
            "howTitle": "从列表到执行只需三步。",
            "howStep1Title": "选择代币",
            "howStep1Body": "选择你持有的任何 Sui 代币类型。选择器按持有量排序,显示每个资产的可用余额。",
            "howStep2Title": "拖放接收者列表",
            "howStep2Body": "粘贴 CSV 或拖放文件。签名前在本地验证每个地址 —— 无效行立即显示，而非事后。",
            "howStep3Title": "一次签名，在一个 PTB 中执行",
            "howStep3Body": "合约原子化地将代币分发给每个接收者。如果任何单笔转账失败,整个批次都会回滚 —— 无部分空投,无卡住的交易。",
            "activityEyebrow": "整个 Pandabox",
            "activityTitle": "最近空投",
            "activityEmpty": "此包暂无空投 —— 你的可能是第一个。",
            "activityCount": "{count, plural, other {# 次空投}}",
        },
    },
    "zh-TW": {
        "items_airdrop": {
            "name": "空投 · 批量發送",
            "tagline": "在一筆簽名交易中將 Sui 代幣分發到最多 300 個錢包。",
            "description": "貼上 CSV，簽名一次,接收者依序到帳。專為代幣發行、貢獻者獎勵與社群空投而設計 —— 適用於無法逐筆簽名的場景。",
            "cap1": "批量發送 · 每筆簽名 PTB 最多 300 個接收者",
            "cap2": "簽名前在本地驗證每個地址",
            "cap3": "按接收者收取固定 SUI 費用 · 無管理員覆寫，無保留",
        },
        "airdrop": {
            "metaTitle": "空投 · Pandabox",
            "eyebrow": "鏈上 · 空投",
            "headline": "一次簽名。多個錢包。",
            "subtitle": "在一筆簽名 PTB 中將 Sui 代幣分發到接收者清單。合約強制執行上限、費用與總額 —— 無需鏈下信任。",
            "ctaCompose": "建立空投",
            "ctaActivity": "最近空投",
            "statFee": "費用 / 接收者",
            "statMax": "最大 / 批次",
            "statLifetime": "累計發送",
            "statStatus": "狀態",
            "statStatusLive": "運行中",
            "statStatusPaused": "已暫停",
            "statSource": "Sui 主網即時",
            "statRevalidate": "每 60 秒重新整理",
            "traitOneSig": "一次簽名",
            "traitAtomic": "原子化 —— 全部成功或全部回滾",
            "traitAnyCoin": "任何 Sui 代幣類型",
            "traitFee": "每接收者 {fee} SUI",
            "traitLearn": "空投運作方式",
            "panelEyebrow": "建立",
            "panelTitle": "接收者清單",
            "panelEmpty": "貼上 CSV、拖放檔案或匯入 JSON 開始。",
            "panelPlaceholder": "在此處拖放你的清單 —— 每行一個地址和金額,或貼上 JSON。",
            "howEyebrow": "運作方式",
            "howTitle": "從清單到執行只需三步。",
            "howStep1Title": "選擇代幣",
            "howStep1Body": "選擇你持有的任何 Sui 代幣類型。選擇器依持有量排序,顯示每個資產的可用餘額。",
            "howStep2Title": "拖放接收者清單",
            "howStep2Body": "貼上 CSV 或拖放檔案。簽名前在本地驗證每個地址 —— 無效行立即顯示,而非事後。",
            "howStep3Title": "一次簽名,在一個 PTB 中執行",
            "howStep3Body": "合約原子化地將代幣分發給每個接收者。如果任何單筆轉帳失敗,整個批次都會回滾 —— 無部分空投,無卡住的交易。",
            "activityEyebrow": "整個 Pandabox",
            "activityTitle": "最近空投",
            "activityEmpty": "此套件尚無空投 —— 你的可能是第一個。",
            "activityCount": "{count, plural, other {# 次空投}}",
        },
    },
}


def main() -> None:
    root = pathlib.Path(__file__).parent.parent / "messages"
    if not root.exists():
        raise SystemExit(f"messages/ not found at {root}")

    for locale, payload in TRANSLATIONS.items():
        path = root / f"{locale}.json"
        if not path.exists():
            print(f"  ! skip {locale} — file not found")
            continue
        d = json.loads(path.read_text())
        # Overwrite the two surfaces; leave everything else untouched.
        d.setdefault("tools", {}).setdefault("items", {})["airdrop"] = (
            payload["items_airdrop"]
        )
        d["airdrop"] = payload["airdrop"]
        path.write_text(json.dumps(d, indent=2, ensure_ascii=False) + "\n")
        print(f"  ✓ {locale}")


if __name__ == "__main__":
    main()
